theme: jekyll-theme-minimal

title: ğŸ¤– â˜•ï¸
description: The personal blog of @iamhepto

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "@iamhepto"

github:
  is_project_page: false
  is_user_page: false